name: Linux build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [project1, project2, project3, project4]
    container: ghcr.io/lballabio/quantlib-swig-devenv:python3
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        make -C ${{ matrix.project }} build
    - name: Run
      run: |
        make -C ${{ matrix.project }} test
